version: '3.8'

services:
    wasm-rs:
        build: ./wasm-rs
        volumes:
            - ./wasm-rs:/root

    serv:
        build: ./serv
        volumes:
            - ./serv/public:/app
            - ./wasm-rs/pkg:/app/wasm
        ports:
            - "8080:8080"
